---
title: "Lab 1"
date: 02-10-2026
format: html
---


```{r}

install.packages(("ggspatial"))

```


```{r}
#| eval: true
#| message: false
#| warninig: false


# load in packages 

library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
library(ggspatial)


```



```{r}

ei_points <- st_read(here("Week1lab", "data", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("Week1lab", "data", "ei_elev.tif"))
ei_borders <- st_read(here("Week1lab", "data", "ei_border.gpkg"))
ei_roads <- st_read(here("Week1lab", "data", "ei_roads.gpkg"))

```



```{r}

# Create a single object map

tm_shape(ei_borders) + 
    tm_polygons() +
tm_shape(ei_roads) +
    tm_lines()+
tm_layout(main.title = "Easter Island")




```

```{r}

filter <- ei_points |> 
    filter(type == "volcano")


```

```{r}

# make it an interactive map

tmap_mode("view")


```
```{r}

# Create a multiple object map with tmap

tm_shape(ei_elev) +
    tm_raster(col.scale = tm_scale_continuous(values = "-viridis"),
    col.legend = tm_legend(title = "Elevation (m asl)")) + 

tm_graticules() +

tm_shape(ei_roads) +
    tm_lines(lwd = 1) +

tm_shape(ei_points) +
    tm_symbols(shape = 24,
    size = "elevation",
    size.legend = tm_legend("Volcanoes (m asl)"),
    fill = "red") +

tm_compass(position = c("right", "top")) +

tm_scalebar(text.size = 0.3, position = c("right", "bottom")) +

tm_title("Easter Island")

```

```{r}

tmap_mode("plot")

```

```{r}

# Making it with GGplot

# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)


ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "#343a40") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +      # legend title with units


   ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                     which_north = "true") + # point to north pole
   ggspatial::annotation_scale(location = "bl",              # bottom left
                               width_hint = 0.5) +           # proportion of map area the scalebar should occupy
   labs(title = "Easter Island") +
   theme_minimal()


```